# General parameters
dataset: Sim_Hirano_Imbens
output_dir: '.'
save_res: True
save_model: False
binary_treatment: False
use_bnn: True

# Parameters for iterative updating algorithm
z_dims: [1,1,1,7]
v_dim: 200
lr_theta: 0.0001
lr_z: 0.0001
g_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]

# Parameters for EGM initialization
kl_weight: 0.0001
lr: 0.0002
g_d_freq: 5
use_z_rec: True
e_units: [64,64,64,64,64]
dz_units: [64,32,8]