# General parameters
dataset: Sim_Colangelo
output_dir: '.'
save_res: True
save_model: True
binary_treatment: False
use_bnn: True

# Parameters for iterative updating algorithm
z_dims: [5,5,5,5]
v_dim: 100
lr_theta: 0.0001
lr_z: 0.0001
g_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]
kl_weight: 0.0001

# Parameters for EGM initialization
lr: 0.0002
g_d_freq: 5
use_z_rec: True
e_units: [64,64,64,64,64]
dz_units: [64,32,8]